apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource
resources:
  - ../../base
images:
  - name: ghcr.io/wynnsource/wynnsource-server
    newTag: latest
labels:
  - pairs:
      app.kubernetes.io/instance: wynnsource-prod
    includeSelectors: false
patches:
  - target:
      kind: Deployment
      name: wynnsource-server
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WCS_SENTRY_ENVIRONMENT
          value: production
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WCS_SENTRY_TRACES_SAMPLE_RATE
          value: "0.1"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: WCS_SENTRY_PROFILES_SAMPLE_RATE
          value: "0.1"
