apiVersion: v1
kind: ConfigMap
metadata:
  name: wynnsource-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
