"""added raid gambits

Revision ID: 8129be0ee115
Revises: b6251978ce59
Create Date: 2026-04-08 17:51:11.189952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8129be0ee115'
down_revision: Union[str, Sequence[str], None] = 'b6251978ce59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gambits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('rotation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consensus_data', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_recalc', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region', 'rotation_start', name='uq_gambit_key')
    )
    op.create_table('gambit_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gambit_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mod_version', sa.String(length=50), nullable=False),
    sa.Column('gambit_names', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('gambit_descriptions', sa.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['gambit_id'], ['gambits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gambit_submissions_gambit_id'), 'gambit_submissions', ['gambit_id'], unique=False)
    op.create_index(op.f('ix_gambit_submissions_user_id'), 'gambit_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gambit_submissions_user_id'), table_name='gambit_submissions')
    op.drop_index(op.f('ix_gambit_submissions_gambit_id'), table_name='gambit_submissions')
    op.drop_table('gambit_submissions')
    op.drop_table('gambits')
    # ### end Alembic commands ###
