"""init

Revision ID: b6251978ce59
Revises: 
Create Date: 2026-02-27 17:35:06.317999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6251978ce59'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', name='uq_beta_item_name')
    )
    op.create_table('pools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pool_type', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('rotation_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotation_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consensus_data', sa.ARRAY(sa.LargeBinary()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('needs_recalc', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pool_type', 'region', 'page', 'rotation_start', name='uq_pool_rotation_key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('creation_ip', sa.String(), nullable=False),
    sa.Column('common_ips', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_token'), 'users', ['token'], unique=True)
    op.create_table('pool_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('client_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mod_version', sa.String(length=50), nullable=False),
    sa.Column('fuzzy', sa.Boolean(), nullable=False),
    sa.Column('item_data', sa.ARRAY(sa.LargeBinary()), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['rotation_id'], ['pools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_submissions_rotation_id'), 'pool_submissions', ['rotation_id'], unique=False)
    op.create_index(op.f('ix_pool_submissions_user_id'), 'pool_submissions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pool_submissions_user_id'), table_name='pool_submissions')
    op.drop_index(op.f('ix_pool_submissions_rotation_id'), table_name='pool_submissions')
    op.drop_table('pool_submissions')
    op.drop_index(op.f('ix_users_token'), table_name='users')
    op.drop_table('users')
    op.drop_table('pools')
    op.drop_table('beta_items')
    # ### end Alembic commands ###
