apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource-dev
resources:
  - ../../base
images:
  - name: ghcr.io/wynnsource/wynnsource-server
    newTag: dev-latest
labels:
  - pairs:
      app.kubernetes.io/instance: wynnsource-dev
    includeSelectors: false
patches:
  - target:
      kind: Deployment
      name: wynnsource-server
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: WCS_VERSION_SUFFIX
            value: "-beta"
