apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wynnsource-pg
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
  storage:
    size: 5Gi
    storageClass: longhorn
  postgresql:
    parameters:
      max_connections: "100"
  bootstrap:
    initdb:
      database: wcs_db
      owner: wynnsource
  backup:
    volumeSnapshot:
      className: longhorn-snapshot
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: wynnsource-pg-daily
spec:
  schedule: "0 15 3 * * *"
  backupOwnerReference: self
  cluster:
    name: wynnsource-pg
  method: volumeSnapshot
