apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource-dev
resources:
- postgres.yaml
- redis.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- migration-job.yaml
images:
- name: ghcr.io/wynnsource/wynnsource-server
  newName: ghcr.io/wynnsource/wynnsource-server
  newTag: e3d81b70bc888f585ed00c07c931afb6b99cc22c
