apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource-dev
resources:
- postgres.yaml
- redis.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- migration-job.yaml
images:
- name: ghcr.io/wynnsource/wynnsource-server
  newName: ghcr.io/wynnsource/wynnsource-server
  newTag: d83720affedcd7ca8fca47d50140579138bb3bcc
