apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource-dev
  # - configmap.yaml
resources:
- postgres.yaml
- redis.yaml
- deployment.yaml
- service.yaml
- migration-job.yaml
images:
- name: ghcr.io/wynnsource/wynnsource-server
  newName: ghcr.io/wynnsource/wynnsource-server
  newTag: 9fde573539b021c8bec626ed16d6d903bbabdcaa
